require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - exe/**/*
    - vendor/**/*

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Favor more explicit contexts over limited nesting.
RSpec/NestedGroups:
  AllowedGroups:
    - context
