# frozen_string_literal: true

require_relative 'database'

module Destination
  # Informix destination for data exports.
  class Informix < Database
    # Informix has no `REPLACE INTO` equivalent, so records are upserted
    # explicitly: update any existing row matching `unique_key`, otherwise
    # insert a new one.
    #
    # @param record [Hash] Record to add to the destination.
    #
    # @raise [ArgumentError] When `unique_key` isn't configured, or the
    #   record is missing a value for one of its columns.
    def add_record(record)
      table = db[@destination_config.fetch(:table).to_sym]
      record = record.transform_keys(&:to_sym)

      key_values = record.slice(*key_columns)
      missing_keys = key_columns - key_values.keys
      raise ArgumentError, "Record is missing key columns: #{missing_keys.join(', ')}" unless missing_keys.empty?

      blank_keys = key_values.select { |_column, value| value.nil? || value.to_s.strip.empty? }.keys
      raise ArgumentError, "Record has blank key columns: #{blank_keys.join(', ')}" unless blank_keys.empty?

      db.transaction do
        table.insert(record) if table.where(key_values).update(record).zero?
      end
    end

    private

    def defaults
      super.merge({ adapter: :ibmdb, port: 9089, security: nil })
    end

    # Destination columns (from `unique_key`) that uniquely identify a
    # record. `id` can't be used for this since it's a serial column
    # generated by Informix on insert, so we have no way of knowing it
    # ahead of time for a record that already exists.
    #
    # @raise [ArgumentError] When `unique_key` isn't configured.
    def key_columns
      columns = Array(@destination_config[:unique_key]).map(&:to_sym)
      raise ArgumentError, 'destination.unique_key is required for Informix' if columns.empty?

      columns
    end
  end
end
