log_level: debug
match_level: 2
match_score: 5
filters:
  - NonHuman
  - filter: ValueIs
    field: TYPE
    value: DEF
    inverse: false

destination:
  type: Mongo
  database: people
  collection: people
  hosts:
    - "mongo:27017"
  username: root
  password: mongodb
  field_map:
    ENTITY_ID: person_id
    DATABASE: database
    PARTY_ID: party_id
    MATCH_SCORE: match_score
    RELATED_RECORD_ID: potential_person_id
    RELATED_MATCH_SCORE: potential_match_score
  export_file: /etc/cmr/export/export.json
  transformations:
    - transform: SplitValue
      field: RECORD_ID
      delimiter: "-"
      parts:
        0: DATABASE
        1: PARTY_ID
